spring:
  application:
    name: gateway-app

zuul:
  prefix: /api
  sensitive-headers: Cookie,Set-Cookie
  routes:
    customer-api:
      path: /customers/**
      serviceId: customer
      stripPrefix: false

    credit-api:
      path: /loans/**
      serviceId: loans
      stripPrefix: false

    dashboard:
      path: /dashboard/**
      serviceId: dashboard
      stripPrefix: false
server:
  port: 8886

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8882/eureka/
    registerWithEureka: false

logging:
  level:
    ROOT: INFO